<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Import Orders and Conversion Rates</title>
    <link rel="stylesheet" href="css/styles.css">
    <link rel="stylesheet" href="http://jqueryvalidation.org/files/demo/site-demos.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/jquery.validate.js"></script>
    <script type="text/javascript" src="js/validations.js"></script>
</head>
<body>
<form id="uploadorders" method="post" enctype="multipart/form-data">
    <div id="page-wrapper">
        <h1>Files to read</h1>
        <div>
            <label for="orderfile">Order File:</label>
            <input type="file" id="orderfile" name="orderfile">
        </div>
        <div>
            <label for="ratesfile">Rates File:</label>
            <input type="file" id="ratesfile" name="ratesfile">
        </div>
        <div>
            <label for="currency">Currency to use in the process</label>
            <select id="currency" name="currency">
                <option value="">Select one currency</option>
                <option value="CHF">CHF</option>
                <option value="EUR">EUR</option>
            </select>
        </div>
        <br />
        <div>
            <label for="getcsv">Get the CSV right Now</label>
            <input type="checkbox" name="getcsv" id="getcsv">
        </div>
    </div>
    <br />
    <div class="submit-section">
        <input type="submit" value="Export">
    </div>
</form>
</body>
</html>
